### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ddmee** [kennethreitz/pipenv-sublime#5]
Hi,

The package isn't available on packagecontrol. At least, if it is, I can't find it. 

I tried to manually install it. I've never done that before with a sublime package. But package control keeps deleting the pipenv directory if I put it into /sublime text 3/Packages

Can you give us installation instructions or make it available on packagecontrol?

Sorry about that,

Donal

**Comment by nathanjr** [comment]
Hi Donal,

You need to remove the file _package-metadata.json_ before manually installing pipenv-sublime package (see https://forum.sublimetext.com/t/sublime-keeps-deleting-my-loose-packages/15691).

This should stop Sublime from thinking this is a rogue package and gobbling it up.

Steps would go something like this:

1. download pipenv-sublime repository as zip
2. extract zip to a local folder
3. remove _package-metadata.json__ from extracted pipenv-sublime-master folder
4. create zip from contents of pipenv-sublime-master folder
5. change zip extension to .sublime-package
6. copy created .sublime-package file to /sublime text 3/Installed Packages
7. restart sublime text

I believe that pipenv-sublime has been submitted to packagecontrol but not yet added. Hopefully it'll be there soon.

Cheers,

Nathan.

**Comment by ddmee** [comment]
Thanks Nathan. It took me a while to get around to trying out your steps. Those steps did help me fix the issue in the end, so I have the pluggin installed, thankfully. It does seem to be taking quite a while to get it listed on the package index. I guess the submission was refused?

**Comment by paterit** [comment]
Nathan. I can't make it work. Any idea when it will be available via Package Controller?

**Comment by jamesstidard** [comment]
@paterit I was able to install by within Sublime: 

- **command pallet:** Package Control: Add Repository
- **paste:** https://github.com/kennethreitz/pipenv-sublime
- **command pallet:** Package Control: Install Package
- **search:** pipenv-sublime

However, I'm yet to get any commands to show up... maybe you'll have better luck from there. Report back if you do :)

**Comment by boonhapus** [comment]
I'll second @jamesstidard ... ~~I can install following those directions~~, but am unable to run any commands. @kennethreitz @nathanjr 

ed/
Actually, it looks like running those instructions does not install it after all. It ends with the same error as #3 .

**Comment by paterit** [comment]
@jamesstidard - thanks for your instructions. It ends up as you described so without commands but following your information from #3 I switched package address to your fork: https://github.com/jamesstidard/pipenv-sublime and then it worked and with commands.
